Repository Pirate-Weather/pirateweather, pull requests merged in 2025-01, with the labels that each got.

#393 Update KongGatewayInfrastructure.md
  docs/Blog/KongGatewayInfrastructure.md
Labels: documentation, bugfix, awaiting developer response

#403 Add currentDay Ice/Liquid/Snow to the data points available in V2
  docs/API.md
Labels: documentation

#358 Create Pull Request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: meta
